GET http://localhost:3000/places?text=av governador valadares, betim, 1000

###
GET http://localhost:3000/places?text=av amazonas, belo horizonte, 1000

###
@originId = EkZBdi4gR292LiBWYWxhZGFyZXMsIDEwMDAgLSBTYW50byBBZm9uc28sIEJldGltIC0gTUcsIDMyNjIzLTU3NSwgQnJhc2lsIjESLwoUChIJja7gMwfdpgARgN9V_RFivpEQ6AcqFAoSCfmsiD4H3aYAEdRlj37c-uzz
@destinationId = ChIJPUqddeKZpgARusD9CDpIBDQ

###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}